version: '3.7'

services:
  server:
    image: server
    build:
      context: ./nginx
    ports:
      - "80:5000"
    volumes:
      - static_data:/static
  db:
    image: db
    build:
      context: ./postgres
    env_file:
      - pg.env
    volumes:
      - db_data:/var/lib/postgresql/data/
  drf:
    image: drf
    build:
      context: .
    env_file:
      - drf.env
    volumes:
      - static_data:/static

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres/pg_data
  static_data:
